title: Purple SFD  # You can add your name here

logo: me.png # Use a relative path to logo image 

description: Cyber Security Researcher & Digital Forensics # Fix hyphenation 

show_downloads: False # Fix spelling

theme: jekyll-theme-minimal 

email: purple@sfd.com # Allow visitors to contact you
